### ISSUE TITLE
Animation errors with scroll behavior : smooth

### ISSUE THREAD

**Issue by tetrabirk** [patrickmatte/scroll-capture#14]
Hi, the animations don't work correctly with the css property "html{scroll-behavior: smooth}". In the meantime I simply deactivate it with the dev-tools and everything works perfectly. Thanks for your work

**Comment by patrickmatte** [comment]
Thanks for reporting this. Maybe I can try to set the scroll-behavior to auto when starting the animation and set it back to smooth after it is done.
