### ISSUE TITLE
Console Error on click - currently unusable

### ISSUE THREAD

**Issue by benjaminelwoods** [patrickmatte/scroll-capture#25]
### Console Errror

`content.js:8 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'clone')
    at wt.deserialize (content.js:8:82065)
    at content.js:8:169411
deserialize @ content.js:8
(anonymous) @ content.js:8
Promise.then (async)
startNextBranch @ content.js:8
start @ content.js:8
start @ content.js:8
_hideComplete @ content.js:8
tasksComplete @ content.js:8
start @ content.js:8
_startTransitions @ content.js:8
(anonymous) @ content.js:8
setTimeout (async)
changeTheLocation @ content.js:8
set location @ content.js:8
(anonymous) @ content.js:8
(anonymous) @ content.js:8
(anonymous) @ content.js:8`

**Comment by patrickmatte** [comment]
Thanks for the error log. I had to remove the JS action to be compatible with Chrome extension manifest V3. I'm wondering if this error could be caused by the extension reading the cookie and trying to rebuid the last list of actions which could include a JS action. Could you try to remove the extension and re-install it? That should clear the cookie.
https://chrome.google.com/webstore/detail/scroll-capture/egmhoeaacclmanaimofoooiamhpkimkk/

**Comment by benjaminelwoods** [comment]
Re-installing it did the trick - any likelihood of the JS action being reinstated down the line?

**Comment by patrickmatte** [comment]
Unfortunately, the extension manifest v3 strictly prohibits the use of eval or new Function so it is impossible to execute a string of code that isn't part of the extension bundle. How were you using the JS action?

**Comment by benjaminelwoods** [comment]
Ah what a shame - all good!

I was actually using it to inject css before I recorded a video so that I could hide the scrollbar of the page and prevent my cursor from being recorded - among other things like hiding specific elements etc.

**Comment by patrickmatte** [comment]
Interesting. I could add options to hide the cursor and the scrollbar while recording. I could probably replace the old JS action with a CSS injection action.

**Comment by benjaminelwoods** [comment]
That would be fantastic!

**Comment by patrickmatte** [comment]
I pushed an update with toggles to hide the scroll bars and cursor in the settings. Let me know if you have other feature requests.

**Comment by benjaminelwoods** [comment]
Great stuff! Works a charm :) - The only thing would be CSS injection if you get around to it. But I'd be happy to let you know if I think of anything else 👍
