### ISSUE TITLE
Stuttering/jumping recording

### ISSUE THREAD

**Issue by benjaminelwoods** [patrickmatte/scroll-capture#26]
I've tried the varying encoding and bitrate options in different combinations and there is often quite bad stuttering or jump-spikes throughout the clip. Is this a performance issue that can be remedied on the user-end or something more involved that needs to be optimised within the code?

Here's two examples of the same website (had to upload to Vimeo).

**[Example 1](https://vimeo.com/888498377?share=copy)**
File Format: webm
Encoding: av1 - 64Mbps
_Window size: 1533px by 1533px_

**[Example 2](https://vimeo.com/888498392?share=copy)**
File Format: x-matroska
Encoding: vp9 - 64Mbps
_Window size: 1533px by 1533px_

**Comment by patrickmatte** [comment]
Try to bring down the bitrate, I augmented the max limit but I think 16mbps
is more than enough for vp9. Unless you have a very large resolution. Vp8
and h264 tend to be more fluid but quality is less than vp9.

I’ll add a routine that checks it the system supports the different codecs
and file formats. I read that chrome supported mkv but perhaps it isn’t
true for all platforms.

Le dim. 26 nov. 2023 à 16:37, Ben Elwood ***@***.***> a
écrit :

**Comment by benjaminelwoods** [comment]
- vp9: Doesn't seem to have resolved the issue much using vp9 - tried bitrates 2, 6, 12 & 16mbps all with similar stuttering.
- vp8: Terrible quality, certainly smoother though at 8 & 16mbps.
- av1: Tried 4, 6, & 16mbps - probably the best quality but the worst stuttering/jumping.

I'm zooming out to 75% on the page at a 1:1 ratio.

**Comment by patrickmatte** [comment]
What are the tech specs of the computer you are using to capture? CPU, GPU, RAM?

**Comment by patrickmatte** [comment]
Ok then it's not a computer performance issue. I have an old mac with an intel processor from 2018 and the captured video is a lot smoother than what you sent. There's not much I can do to optimize the performance.  Maybe try to just record the screen with quicktime and use the play button to play the list of actions and see if the performance is better that way.

**Comment by benjaminelwoods** [comment]
Yeah I found it worked well with using the macOS built in screen recorder.

I remoted into my PC at home and that provided a much better output. Maybe it's an issue with Apple Silicon..
