### ISSUE TITLE
Feature Request: "Record Audio" toggle

### ISSUE THREAD

**Issue by benjaminelwoods** [patrickmatte/scroll-capture#28]
If you get time, would be awesome to have a toggle that allows you to disable audio recording particularly when there isn't any audio to record.

**Comment by patrickmatte** [comment]
In the settings panel, I added toggle buttons next to the audio and video codecs. On top of recording video without audio, you can now even record audio only...

**Comment by benjaminelwoods** [comment]
Perfect! Thank you! :)
