### ISSUE TITLE
Feature request: add a 'refresh' or similar option to play on-load animations when recording

### ISSUE THREAD

**Issue by benjaminelwoods** [patrickmatte/scroll-capture#29]
Would be awesome to have a toggle that 'reloads' the page before record to capture on-load animations etc.

This would likely coincide with a previous request of mine to have custom CSS injected as users may want to have elements hidden 
or removed on-load before capture.

**Comment by benjaminelwoods** [comment]
Epic! Looking forward to it.

**Comment by patrickmatte** [comment]
You can try the 'load url' action in the latest update. And you can now build a timeline that goes over multiple html pages. The sequence of actions starts again when the new page is loaded.
