### ISSUE TITLE
Feature Request: Option to input text

### ISSUE THREAD

**Issue by azeem-io** [patrickmatte/scroll-capture#30]
It would be great if you add an option to input text in a selected text field. Doesn't matter if the text is written letter by letter or the entire sentence is pasted all at once. I believe this would provide greater flexibility and efficiency for various use cases.

**Comment by patrickmatte** [comment]
I'm not sure about what you're asking? Do you have an example?

**Comment by mikesnoeren** [comment]
I think this is a feature that is currently missing. I tried making a demo capture of how to use a tool we've built, and in this tool you are required to input text in a text field, but currently this is not possible.

**Comment by patrickmatte** [comment]
Oh I see what you mean, got it. That should be easy to add. I'm a little busy these days but you can expect this in the next release.
