### ISSUE TITLE
Unable to insert parameters in timeline settings

### ISSUE THREAD

**Issue by Garavani** [patrickmatte/scroll-capture#31]
Hi Matte!

This seems to be an absolutely awesome plugin! Exactly what I was trying to achieve! Thanks so much!
However, I seem to be unable to insert the parameters (time, position etc.) into the fields or use the arrows on the right of each field to change the values. The only thing I can interfere with is the dragging of the ease handlers. (great idea, by the way!)

What am I doing wrong? Working on Google Chrome Mac Ventura.

Thank you again!
Best,
Stefan

<img width="404" alt="Bildschirmfoto 2023-12-05 um 12 05 48" src="https://github.com/patrickmatte/scroll-capture/assets/7022102/52e7d590-60de-438e-a03a-3716f43d3b91">

**Comment by patrickmatte** [comment]
Hi Stefan,
Can you give me the url so I can try it out?

Le mar. 5 déc. 2023 à 06:06, Stefan Seifert ***@***.***> a
écrit :

**Comment by Garavani** [comment]
Hi Patrick!

Of course. This is the one where I tried:


https://www.elementi-design.com/ibak-prototype/￼


Thanks very much! Very kind of you!

Best,
Stefan

**Comment by patrickmatte** [comment]
The url goes to the 404 page. I tried the extension on the homepage, everything seemed to work normally.

**Comment by Garavani** [comment]
Hi Patrick,

thanks for your type.

Weird though, I tested the url I sent and it was ok. Here again:

https://www.elementi-design.com/ibak-prototype/

However I don’t think it depends on a specific url as long as I can not use the input fields in your beautiful mask with the values.
As said the idea is brlllant, but I cannot type into the fields with the numbers highlighted in white and also not use the tiny arrows aside the fields.
Could be something with Mac Ventura or some browser preference. I updated my Chrome, didn’t help.

Thanks so much
Best,
Stefan

**Comment by patrickmatte** [comment]
The problem is within the website. I see a bunch of errors in the JS console.

`803[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>`

 It looks like the code is trying to block every event. I can't even right-click to bring up the browser's contextual menu.
