### ISSUE TITLE
"Add a scroll animation" button does not work

### ISSUE THREAD

**Issue by SilviaMalavasi** [patrickmatte/scroll-capture#32]
I can't add a scroll animation to the timeline if Chrome windows is heigher than the screen or it falls out of the screen.

**Comment by patrickmatte** [comment]
Can I see the url you are trying to capture?

**Comment by patrickmatte** [comment]
The scroll action detects which html elements can be scrolled. If it can't detect any scrollable elements, then it is impossible and useless to add a scroll action. It is possible that a website hijacks the regular 'scroll' events and uses the 'wheel' event for a custom scrolling experience, I've seen it happen before. But in that case it it impossible to trigger the scrolling as dispatching the 'wheel' event is deemed unsecure and is ignored by the browser. Scroll capture can only scroll html element containers using the scrollTop and scrollLeft properties.

**Comment by patrickmatte** [comment]
Without a link to replicate the issue, there's not much I can do
