### ISSUE TITLE
Error / Won't Run on Specific Site

### ISSUE THREAD

**Issue by ThioJoe** [patrickmatte/scroll-capture#34]
When clicking on the extension while on at least one site, the extension doesn't seem to work (it doesn't do anything, doesn't show the usual pop up window at all).

So far I've only noticed the problem on this site: https://www.bitdefender.com/solutions/scamio.html (It seems like other pages on Bitdefender.com are also affected)

In the Chrome dev console it shows this:
```
content.js:1 Uncaught SyntaxError: Unexpected token (1:13) (at content.js:1:71902)
    at xt.raise (content.js:1:71902)
    at tt.unexpected (content.js:1:17592)
    at tt.expect (content.js:1:17547)
    at gt.parseTemplate (content.js:1:63533)
    at gt.parseExprAtom (content.js:1:58450)
    at gt.parseExprSubscripts (content.js:1:53490)
    at gt.parseMaybeUnary (content.js:1:52842)
    at gt.parseExprOps (content.js:1:51069)
    at gt.parseMaybeConditional (content.js:1:50722)
    at gt.parseMaybeAssign (content.js:1:50061)
xt.raise	@	content.js:1
tt.unexpected	@	content.js:1
tt.expect	@	content.js:1
gt.parseTemplate	@	content.js:1
gt.parseExprAtom	@	content.js:1
gt.parseExprSubscripts	@	content.js:1
gt.parseMaybeUnary	@	content.js:1
gt.parseExprOps	@	content.js:1
gt.parseMaybeConditional	@	content.js:1
gt.parseMaybeAssign	@	content.js:1
gt.parseExpression	@	content.js:1
Z.parseExpressionAt	@	content.js:1
se	@	content.js:1
Gs	@	content.js:1
(anonymous)	@	content.js:1
set scope	@	content.js:1
ui	@	content.js:1
wi	@	content.js:1
(anonymous)	@	content.js:1
(anonymous)	@	content.js:1
(anonymous)	@	content.js:1
```

I enabled 'collect errors' in the chrome extension settings and these are what it show:
<img width="487" alt="image" src="https://github.com/patrickmatte/scroll-capture/assets/12518330/5a0314e3-5316-41e4-8744-e65af30e6746">

<img width="499" alt="image" src="https://github.com/patrickmatte/scroll-capture/assets/12518330/c78f38e3-a599-41b9-a6af-11743ed5ffe7">

I tried copying the text from the stack trace box, but it's actually got 300k characters of text in there despite being 1 line.

--------------

Currently I'm running version 0.2.6 of the extension, but I haven't used the extension in a while so I'm not sure if previous versions are affected.

**Comment by patrickmatte** [comment]
Thank I'll try to dig in

**Comment by patrickmatte** [comment]
I see what is happening. I'll push another version with a fix later today.
