### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by ThioJoe** [patrickmatte/scroll-capture#35]
Not sure if this is related to #34, but I noticed on Facebook.com pages, the video capture window doesn't seem to have any symbols:

<img width="329" alt="image" src="https://github.com/patrickmatte/scroll-capture/assets/12518330/c511f4ac-804a-43ae-b434-a0cb49149f84">

I've tried on both on the Stable and Beta versions of chrome and in Incognito mode. I've checked on several other sites but this seems to be the only one it does it on.

And in this case, it does not seem to produce any errors either in the dev console or after enabling "collect errors" for the extension.

**Comment by patrickmatte** [comment]
Thanks for reporting this, I thought I had already fixed it. It's just this facebook css rule that is messing up the icons.
`#facebook .system-fonts--body span {
    font-family: inherit;
}`
