### ISSUE TITLE
Recording is not downloadable

### ISSUE THREAD

**Issue by miller-thinkso** [patrickmatte/scroll-capture#38]
After setting up the Screen Capture how I want and click to record for download, a bunch of weird code is displayed and I still can't download the video.

Here's a video of what's happening.
https://www.loom.com/share/aff38deafea1403fab7672692a798e5c?sid=6480d5d3-3da0-4ef4-9c0d-ee22fa5bedc2

**Comment by patrickmatte** [comment]
The video capture works on my computer. 

https://github.com/patrickmatte/scroll-capture/assets/435963/d830175f-9e10-446a-8dee-47f5aa7b50fc

Could you copy and paste here, all of the little code that is displayed?

**Comment by miller-thinkso** [comment]
Looks like it's working correctly for me now. Thank you!
