### ISSUE TITLE
Video Compression

### ISSUE THREAD

**Issue by swiwidesign** [patrickmatte/scroll-capture#40]
Hi there,
it seems the video compression has changed since the last update and the videos are a lot more blurry. Would be great if there would be an option to choose the compression. An option to get a raw .mov file would be amazing!

Thanks a lot for your work!

**Comment by patrickmatte** [comment]
Just pushed an update, version 0.3.3 can save a video as mp4, webm or mkv. Try webm with VP9 for best quality or VP8 for best framerate. Of course, you can also adjust the bitrate of the video compression. The max is currently 32MB.

Unfortunately, it is impossible to capture the chrome tab with an uncompressed video format.

For the best result, do your video capture with Quicktime if you're on a mac. You can still use scroll capture's automation features by pressing the play all actions button in the bottom right.
