### ISSUE TITLE
Mouse clicks and Hover animations not working

### ISSUE THREAD

**Issue by APalm23** [patrickmatte/scroll-capture#44]
First of what a great tool, thanks! 

I encountered an issue in that I couldn't get clicks of any kind of mouse movements to work. I tried in Windows and Mac, also tried on many different websites.

More specifically I am trying to get it to work so that when I click on the FAQ section's question it opens up and when I click again it closes. Sadly, the extension somehow doesn't register the click.

Website: https://www.habagala.ebsikas.com/

https://github.com/patrickmatte/scroll-capture/assets/116555632/71a3e9be-a3bb-4418-b050-b7af15071740

**Comment by patrickmatte** [comment]
Hi, thanks for sharing this issue. I tried to debug it but I can't find what is missing. The weird thing is that when I manually open the first FAQ item, I can make scroll capture click on the link inside the expanded text and it opens a new window. I just can't open or close the FAQ item. Did you build this? What does the code look like for the open and close of the FAQ item?

**Comment by patrickmatte** [comment]
It looks like framer might be looking for a 'pointerup' event but I still couldn't open and close the faq item. Sorry.

**Comment by APalm23** [comment]
Hey, thanks for the quick response! I also thought that framer is most likely the reason. Anyhow, I managed to show that step by manually clicking when recording so no biggy. Once again, awesome tool!
