### ISSUE TITLE
Cursor visibility

### ISSUE THREAD

**Issue by sbuys** [patrickmatte/scroll-capture#50]
With cursor set to "✅ auto", there isn't a cursor visible in the recording. Scrollbars are visible. Is there another setting somewhere that I'm missing?

**Comment by sbuys** [comment]
Or maybe I misunderstand the feature. I guess there is no emulated cursor to mimic the interactions?

**Comment by patrickmatte** [comment]
The cursor visibility option just toggles your own cursor's visibility. There's currently no fake cursor.

**Comment by patrickmatte** [comment]
<img width="634" alt="scrollbar" src="https://github.com/patrickmatte/scroll-capture/assets/435963/0d0288c4-eb67-4d6e-8527-c81b637709b0">
This is what the panel's scrollbar should look like

**Comment by sbuys** [comment]
Thanks @patrickmatte - makes sense.

Also, thanks for making this extension! Very helpful and fun to use.

**Comment by patrickmatte** [comment]
I have already thought about how to create the fake cursor. I'll try to implement it when I get some time. But probably not before next October.
