### ISSUE TITLE
Scrollbar within Scroll Capture UI missing

### ISSUE THREAD

**Issue by td7932** [patrickmatte/scroll-capture#51]
The scrollbar within the UI seems to be missing. I can add events but can't scroll up and down to change properties and tweak them. I can resize the UI to show more, but it's very limiting. The extension was working fine last week.

<img width="295" alt="image" src="https://github.com/patrickmatte/scroll-capture/assets/173320202/e33f056b-0f66-4a87-ac38-4e3371ecb267">

**Comment by patrickmatte** [comment]
There's nothing wrong with the scroll capture panel. Just try it on another URL. 
Since the panel is added to the html page, sometimes the website's javascript or css code can mess up the panel. The website's developers might be preventing the scroll event to bubble up for some weird reason and that would prevent you from scrolling the panel. There should be a little scrollbar on the side of the panel that you can pull it up and down if scrolling doesn't work. I don't know why you're not seeing it, maybe the website's CSS or one of your other extensions is breaking the little scrollbar on the side of the panel. What URL are you trying to capture?

**Comment by td7932** [comment]
Thanks for the response.

> There should be a little scrollbar on the side of the panel that you can pull it up and down if scrolling doesn't work. I don't know why you're not seeing it, maybe the website's CSS or one of your other extensions is breaking the little scrollbar on the side of the panel.

Regardless of which URL I try, the scrollbar within the panel is not showing up. Like I said, I successfully captured several different websites last week, and the scrollbar within the panel was visible and functioning as expected. The other extensions I'm using haven't changed, so I don't think that's the issue. I'm using Chrome on Windows 11, Version 126.0.6478.115 (Official Build) (64-bit).

**Comment by carolinebeavon** [comment]
I've faced the same issue as above  - 
Seems to be a sizing / zoom issue. 
I fixed it by dragging the right hand side of the panel left and right. 
As the content in the panel gets smaller, the icons across the bottom appear. 

https://github.com/patrickmatte/scroll-capture/assets/68392646/4e29a522-c971-45eb-a1ca-20e3418bf65f

**Comment by patrickmatte** [comment]
This is what the panel should look like when you resize. What URL were you looking at?
https://github.com/patrickmatte/scroll-capture/assets/435963/e6ff9f9d-edee-43cb-8bd6-9aff12702a71

**Comment by carolinebeavon** [comment]
Its the same on all pages I try (for example this https://www.carolinebeavon.com/work and even this one on Github)

(sorry about the terrible quality - recorded trying to capture this page - hope it helps)
https://github.com/patrickmatte/scroll-capture/assets/68392646/d1c5d518-427b-47f6-9ce3-6ea9e7fe601b

**Comment by reinisrozensteins** [comment]
We have the same problem on MAC and this problem start when update Google Crome to 126.0.6478.63 version.

My friend didnt update and for him working fine.

**Comment by patrickmatte** [comment]
Ok I just updated Chrome from 125 to 126 and I'm now seeing this bug too.

**Comment by patrickmatte** [comment]
MP4 video is also broken on Chrome 126 but you can use WEBM video in the meantime.

**Comment by sholom00** [comment]
I'm having this issue as well. Also on Mac and on Chrome 126

**Comment by sholom00** [comment]
As a temporary workaround, albeit a really annoying one, is to inspect element on the interface box and in the **"sc-container"** div, change "overflow: _clip_" to "overflow: **auto**". You will have to do this every time the page reloads.

 <img width="316" alt="Screenshot 2024-06-25 at 10 34 51 AM" src="https://github.com/patrickmatte/scroll-capture/assets/153046316/915a8380-85d7-40af-8188-d568a8a59069">

**Comment by patrickmatte** [comment]
@sholom00 Great idea. Make it easier and add a CSS action like this and press the play button
<img width="607" alt="Capture d’écran, le 2024-06-25 à 10 55 50" src="https://github.com/patrickmatte/scroll-capture/assets/435963/efa94f1c-caa3-448b-b188-5353637f3c13">

**Comment by sholom00** [comment]
Yes! I was just about to post this alternative workaround method as well. Important to note that if you have a page reload as part of your capture sequence, move the css action **below** the page reload. Obvious, but took me a minute to realize why it wasn't adding it. Thanks for adding that!

> @sholom00 Great idea. Make it easier and add a CSS action like this and press the play button <img alt="Capture d’écran, le 2024-06-25 à 10 55 50" width="607" src="https://private-user-images.githubusercontent.com/435963/342784236-efa94f1c-caa3-448b-b188-5353637f3c13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMjc4MzQsIm5iZiI6MTcxOTMyNzUzNCwicGF0aCI6Ii80MzU5NjMvMzQyNzg0MjM2LWVmYTk0ZjFjLWNhYTMtNDQ4Yi1iMTg4LTUzNTM2MzdmM2MxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxNDU4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWVjZTYwZWQ4MjMyYzc2MWQzYTdjNGY5NGJiNjBjNzZmYzExZmU2NjdkNmM1N2Y0NTQ3MWI3YWM3NmZhZGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bg79LLlxAYOtVsKgta_jb1Jr1DGJdtirnDQHS0cGksw">

**Comment by patrickmatte** [comment]
The panel scrolling bug seems to come from flex-grow and flex-shrink not behaving the same way that they used to in Chrome 125 and below. I've filed a bug report.
The issue with MP4 seems to come from Chrome 126 now supporting sreen recording in MP4 format natively without the use of FFMPEG.
I'm super busy with other stuff right now but I'll try to look into this and push a fix asap.

**Comment by patrickmatte** [comment]
The bugs with Chrome 126 are now resolved in version 0.4.5

**Comment by td7932** [comment]
Thank you! Really appreciate it.

**Comment by carolinebeavon** [comment]
Thank you for fixing this so quickly ... it's SUCH a useful tool ...

**Comment by eriiform** [comment]
Hi, I'm using a Mac running Chrome Version 128.0.6613.114 (Official Build) (arm64) and the sidebar is missing for me as well.  It makes it impossible to use, sadly. Using the CSS hack also, unfortunately, doesn't work for me.
<img width="541" alt="Screenshot 2024-08-30 at 2 38 23 PM" src="https://github.com/user-attachments/assets/2bf45ad0-3d7d-47c9-a062-3990c9d255f2">

Any ideas? It's the same running it in Brave 1.69.160

**Comment by patrickmatte** [comment]
What the url of that website? Have you tried the extension on another website?

**Comment by eriiform** [comment]
It's written in the Load URL box. I just checked Screen Capture on other sites and I do see the scroll bar when on them. What do you think is causing the issue?

**Comment by patrickmatte** [comment]
haha. very smart! I'm investigating. It is possible that the webstie uses a custom scroll library which hacks the scroll of the website and that may be intefering with the scroll capture panel scroll. But normally you should see a scrollbar but it looks like the website is also hiding all scrollbars... That's the problem with adding the extension panel in the website, the website's css sometimes messes up the extension panel.

**Comment by patrickmatte** [comment]
Can you add a css action and paste this code in it. Then pless that action's play button to add the css.

`  ::-webkit-scrollbar {
    width: 5px !important;
    height: 5px !important;
    display: block !important;
  }`

**Comment by eriiform** [comment]
This is much better than my workaround. Thank you!
