### ISSUE TITLE
Videos end up corrupted and not playable on most players

### ISSUE THREAD

**Issue by Ourobobross** [patrickmatte/scroll-capture#52]
Last week everything worked fine, today i can't work with the files.
Not sure whats happening.

Quicktime and AfterEffects can't open the files. 
Preview in Slack, VLC and Elmedia work
Tested on both mac and PC

Might be something to do witch the codec since I don't get information about it in the file details

Added both the working file from last week and the broken new one from today

https://github.com/patrickmatte/scroll-capture/assets/102997829/350cae37-acda-4912-a052-5552282aac43
https://github.com/patrickmatte/scroll-capture/assets/102997829/01327db2-672c-4177-8205-3734cecf468d

**Comment by patrickmatte** [comment]
The extension is broken since Chrome 126 was released last week. Scrolling of the panel is broken and MP4 seems broken as well. If you really need to use it, try to roll back to Chrome 125 if possible.

**Comment by Ourobobross** [comment]
Alright will do,
Thanks for the fast answer :)

**Comment by patrickmatte** [comment]
The bugs with Chrome 126 are now resolved in version 0.4.5

**Comment by Ourobobross** [comment]
Thanks a lot. Awesome tool, it's by far the best out there :)
