### ISSUE TITLE
Scroll Capture GUI is zoomed in, can't access controls.

### ISSUE THREAD

**Issue by BloodSugar327** [patrickmatte/scroll-capture#55]
The GUI was working fine on the page but after I ran the script it reloaded zoomed in and now it won't reset on this specific page. Any other page the GUI loads fine still.

[LinkStack](https://linkstack.twocityprinting.com/@twocityprinting)

![Screenshot 2024-08-19 130129](https://github.com/user-attachments/assets/05e520dd-4da7-4688-aee0-9bdf7e36a27d)

**Comment by patrickmatte** [comment]
Thanks for the bug report. Can you give me more details because I don't quite understand what is going on. You mentioned running a script? What script?
And you're talking about a default theme? What theme are we talking about?
