### ISSUE TITLE
Please advise: Input Text and Mouse Event

### ISSUE THREAD

**Issue by BarryTPP** [patrickmatte/scroll-capture#56]
Hi Patrick,

Just learned of scroll capture a few days ago and love it.

Trying to do 2 things that am unable to figure out. Please advise:

1. **Input Text**. I want to paste text into "Value" that would then appear as a vertical numbered list when recording. Is this possible?
2. **Mouse Event**. In a drop down selector, I want to select an item from a list. Is this possible?

Thank you!

Barry

**Comment by patrickmatte** [comment]
1. You can use the input action to enter text into the browser's native <input/> element.

2. For the <select> element, you also use the input action. I don't think you can use MouseEvent to select an option unfortunately. 

https://github.com/user-attachments/assets/c0523495-c619-4d35-b871-d8bcb6a59ada

**Comment by patrickmatte** [comment]
https://github.com/user-attachments/assets/5de428d8-2062-46ac-8a2b-a6d9b4b2cadd

**Comment by BarryTPP** [comment]
Patrick - thank you for these. Both solved the problems I had been having.

**New challenge**: after recording, the video is not available. SC icon shows red in extensions when recording, but then no video appears. Any suggestions?

Thank you again!

Barry

**Comment by patrickmatte** [comment]
What is the url that you are trying to capture? Try reloading the window and capture again. You can also try to run your actions one by one to see if one might be breaking the script. Look at the browser console if there are any errors showing.
