### ISSUE TITLE
JS Console error

### ISSUE THREAD

**Issue by tatenalan** [patrickmatte/scroll-capture#58]
Hello,

I’m having an issue when trying to run the extension on the website rbgrealtor.com. I’ve tested it on some other websites, and it works fine.

When I click on the extension, the pop-up doesn’t open, and I receive the following error in the console:

<img width="386" alt="image" src="https://github.com/user-attachments/assets/72978cf8-5292-4417-a515-10305157dbc8">

Do you know what could be causing this? The site is developed in WordPress. We’ve deactivated the plugins, but the problem persists. We’ve also tried using the extension on other webpages built with the same technology, but we don’t encounter any issues.

I’ve done some further investigation, and the issue was resolved when we switched themes. We were using the Bricks Theme. However, on other sites like ppcbliss.com, which also uses Bricks and the same version, the extension works fine.

Thank you

**Comment by patrickmatte** [comment]
Interesting, thanks for reporting it!

**Comment by patrickmatte** [comment]
Found the problem. I'll try to publish an update later today. Thanks again!

**Comment by tatenalan** [comment]
> Found the problem. I'll try to publish an update later today. Thanks again!

That was fast. I appreciate it
